project:
  type: website
  output-dir: "docs"
  render:
    - index.qmd
    - Models_done_Right.qmd

website:
  title: "Chla Variability of the Med Sea"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Models_done_Right.qmd
        text: Results
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: source


