project:
  type: website
  output-dir: "docs"
  render:
    - index.qmd
    - Models_done_Right.qmd
    - Seasonality_variables.qmd
    - Model_with_lags.qmd
website:
  title: "Chla Variability of the Med Sea"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Models_done_Right.qmd
        text: Results
      - href: Seasonality_variables.qmd
        text: Temporality of Variables
      - href: Model_with_lags.qmd
        text: Model with lags
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: source


