project:
  type: website
  output-dir: "docs"

website:
  title: "Chla Variability of the Med Sea"
  navbar:
    left:
      - href: index.qmd
        text: Home
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: source


