project:
  type: website
  output-dir: "docs"
  render:
    - index.qmd
    - Single_Model.qmd

website:
  title: "Chla Variability of the Med Sea"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Single_Model.qmd
        text: Results
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: source


